import type { Metadata } from "next";

import {
  MantineProvider,
  mantineHtmlProps,
  ColorSchemeScript,
} from "@mantine/core";

import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";

import { TelegramProvider } from "@/context";

import { QueryProvider } from "./query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className="bg-zinc-100">
        <MantineProvider>
          <QueryProvider>
            <TelegramProvider>{children}</TelegramProvider>
          </QueryProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
